config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :photos, only: %i(index new create)

  get 'oauth/my_tweet_app', to: 'sessions#my_tweet_app_oauth', as: :my_tweet_app_oauth
  get 'oauth/callback', to: 'sessions#callback', as: :oauth_callback
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image

  belongs_to :user

  validates :title, presence: true, length: { maximum: 30 }
  validates :image, presence: { message: 'を選択してください' }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    unless current_user
      redirect_to login_path, notice: 'ログインしてください'
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @photos = current_user.photos
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    if @photo.save
      flash[:notice] = '写真がアップロードされました'
      redirect_to photos_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end

private

def photo_params
  params.require(:photo).permit(:title, :image)
end

app/controllers/sessions_controller.rb
require 'net/http'
require 'uri'
require 'json'

class SessionsController < ApplicationController
  MY_TWEET_APP_CLIENT_ID = ENV['MY_TWEET_APP_CLIENT_ID']
  MY_TWEET_APP_CLIENT_SECRET = ENV['MY_TWEET_APP_CLIENT_SECRET']
  REDIRECT_URI = ENV['REDIRECT_URI']

  def new
  end

  def create
    # 未入力チェック
    errors = []
    errors << 'ユーザーIDを入力してください' if params[:user_id].blank?
    errors << 'パスワードを入力してください' if params[:password].blank?

    if errors.any?
      flash[:alert] = errors
      return render :new, status: :unprocessable_entity
    end

    user = User.find_by(login_id: params[:user_id])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'ログインしました'
      redirect_to root_path
    else
      flash[:alert] = 'ログインID、またはパスワードが間違っています。'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'ログアウトしました'
    redirect_to login_path
  end

  def my_tweet_app_oauth
    auth_url = 'http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/authorize?' +
    "response_type=code&" +
    "client_id=#{MY_TWEET_APP_CLIENT_ID}&" +
    "redirect_uri=#{REDIRECT_URI}&" +
    "scope=write_tweet"
    redirect_to(auth_url, allow_other_host: true)
  end

  def callback
    code = params[:code]
    uri = URI('http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/token')
    response = Net::HTTP.post_form(uri, {
      code: code,
      client_id: MY_TWEET_APP_CLIENT_ID,
      client_secret: MY_TWEET_APP_CLIENT_SECRET,
      redirect_uri: REDIRECT_URI,
      grant_type: 'authorization_code'
    })
    token_data = JSON.parse(response.body)
    access_token = token_data['access_token']
    # sessionに保持
    session[:access_token] = access_token

    redirect_to root_path, notice: 'MyTweetAppと連携しました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Photo App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- フラッシュメッセージの表示 -->
    <% flash.each do |key, messages| %>
      <div class="flash">
        <ul>
          <% Array(messages).each do |message| %>
            <li class="flash-<%= key %>"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<%= render 'shared/logout' %>

<h1>写真一覧</h1>
<p><%= link_to 'MyTweetAppと連携', my_tweet_app_oauth_path %></p>
<p><%= link_to '写真を新規にアップロード', new_photo_path %></p>

<% if @photos.any? %>
  <div class="photos-grid">
    <% @photos.each do |photo| %>
      <div class="photo-item">
        <p><%= photo.title %></p>
        <div class="photo-frame">
          <% if photo.image.attached? %>
            <%= image_tag photo.image, class: "uploaded-photo" %>
          <% else %>
            <p>写真がありません</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>まだ写真がアップロードされていません。</p>
<% end %>

app/views/photos/new.html.erb
<%= render 'shared/logout' %>

<h1>写真アップロード</h1>

<%= form_with model: @photo, url: photos_path, local: true do |form| %>
  <% if @photo.errors.any? %>
    <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li class="flash-alert"><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :title, "タイトル" %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, "画像ファイル" %><br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "アップロード" %>
    <%= link_to "キャンセル", photos_path %>
  </div>
<% end %>

app/views/shared/_logout.html.erb
<%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete } %>